const RELEASE_INSTALLER = "https://github.com/TOTO-Toolkit/TOTO-public/releases/download/v0.2.0-public-beta.2/TOTO-Setup-Web.exe";

const copy = {
  en: { nav_demo: "Demo", nav_download: "Download", nav_releases: "Releases", hero_title: "Explore tracking before installing.", hero_copy: "A small, synthetic browser demo for the interaction flow. Your videos, models and calibrations stay local in the desktop application.", try_demo: "Try the demo", download_windows: "Download Windows installer", local_first: "Local-first by design", no_upload: "No upload · no account · no private data in this demo", interactive_label: "INTERACTIVE PREVIEW", demo_title: "Review a tracked frame", synthetic: "Synthetic data", play: "Play", frame: "Frame", overlay: "Overlay", ready: "Ready for review", roi_none: "No ROI selected", person: "Person", visuals: "Visual layers", skeleton: "Skeleton", boxes: "Bounding box", zoom: "Zoom", roi: "ROI", clear: "Clear", draw_roi: "Draw ROI", outside_mask: "Outside mask", analyze: "Analyze selected person", analysis_hint: "Choose a frame and press Analyze to see a reproducible preview metric.", distribution: "PUBLIC DISTRIBUTION", download_title: "Install the complete desktop workflow", download_copy: "The web installer is a small bootstrap. It shows the real download plan, resumes interrupted downloads, verifies SHA-256 and installs the pinned TOTO components atomically.", analyzed: "Preview metric: {score}% confidence · ranked subject Person {person} · frame {frame}" },
  es: { nav_demo: "Demo", nav_download: "Descargar", nav_releases: "Versiones", hero_title: "Explora el tracking antes de instalar.", hero_copy: "Una pequeña demo sintética para probar el flujo. Tus vídeos, modelos y calibraciones permanecen locales en la aplicación de escritorio.", try_demo: "Probar demo", download_windows: "Descargar instalador Windows", local_first: "Local-first por diseño", no_upload: "Sin subir datos · sin cuenta · sin datos privados en esta demo", interactive_label: "VISTA INTERACTIVA", demo_title: "Revisa un frame trackeado", synthetic: "Datos sintéticos", play: "Reproducir", frame: "Frame", overlay: "Overlay", ready: "Listo para revisar", roi_none: "Sin ROI seleccionada", person: "Persona", visuals: "Capas visuales", skeleton: "Esqueleto", boxes: "Caja", zoom: "Zoom", roi: "ROI", clear: "Limpiar", draw_roi: "Dibujar ROI", outside_mask: "Máscara exterior", analyze: "Analizar persona", analysis_hint: "Elige un frame y pulsa Analizar para ver una métrica reproducible.", distribution: "DISTRIBUCIÓN PÚBLICA", download_title: "Instala el flujo de escritorio completo", download_copy: "El instalador web es un bootstrap pequeño. Muestra el plan real, reanuda descargas, verifica SHA-256 e instala los componentes fijados de TOTO de forma atómica.", analyzed: "Métrica de vista previa: {score}% de confianza · sujeto rankeado Persona {person} · frame {frame}" },
  pt: { nav_demo: "Demo", nav_download: "Download", nav_releases: "Versões", hero_title: "Explore o tracking antes de instalar.", hero_copy: "Uma pequena demonstração sintética do fluxo. Seus vídeos, modelos e calibrações permanecem locais no aplicativo desktop.", try_demo: "Testar demo", download_windows: "Baixar instalador Windows", local_first: "Local-first por design", no_upload: "Sem upload · sem conta · sem dados privados nesta demo", interactive_label: "PRÉVIA INTERATIVA", demo_title: "Revise um frame rastreado", synthetic: "Dados sintéticos", play: "Reproduzir", frame: "Frame", overlay: "Overlay", ready: "Pronto para revisão", roi_none: "Nenhuma ROI", person: "Pessoa", visuals: "Camadas visuais", skeleton: "Esqueleto", boxes: "Caixa", zoom: "Zoom", roi: "ROI", clear: "Limpar", draw_roi: "Desenhar ROI", outside_mask: "Máscara externa", analyze: "Analisar pessoa", analysis_hint: "Escolha um frame e pressione Analisar para ver uma métrica reproduzível.", distribution: "DISTRIBUIÇÃO PÚBLICA", download_title: "Instale o fluxo desktop completo", download_copy: "O instalador web é um bootstrap pequeno. Mostra o plano real, retoma downloads, verifica SHA-256 e instala os componentes fixados do TOTO atomicamente.", analyzed: "Métrica de prévia: {score}% de confiança · sujeito Pessoa {person} · frame {frame}" },
  it: { nav_demo: "Demo", nav_download: "Download", nav_releases: "Release", hero_title: "Prova il tracking prima di installare.", hero_copy: "Una piccola demo sintetica del flusso. Video, modelli e calibrazioni restano locali nell'app desktop.", try_demo: "Prova la demo", download_windows: "Scarica installer Windows", local_first: "Local-first per progetto", no_upload: "Nessun upload · nessun account · nessun dato privato", interactive_label: "ANTEPRIMA INTERATTIVA", demo_title: "Esamina un frame tracciato", synthetic: "Dati sintetici", play: "Riproduci", frame: "Frame", overlay: "Overlay", ready: "Pronto per la revisione", roi_none: "Nessuna ROI", person: "Persona", visuals: "Livelli visivi", skeleton: "Scheletro", boxes: "Riquadro", zoom: "Zoom", roi: "ROI", clear: "Cancella", draw_roi: "Disegna ROI", outside_mask: "Maschera esterna", analyze: "Analizza persona", analysis_hint: "Scegli un frame e premi Analizza per vedere una metrica riproducibile.", distribution: "DISTRIBUZIONE PUBBLICA", download_title: "Installa il flusso desktop completo", download_copy: "L'installer web è un bootstrap leggero. Mostra il piano, riprende i download, verifica SHA-256 e installa i componenti TOTO in modo atomico.", analyzed: "Metrica di anteprima: {score}% confidenza · soggetto Persona {person} · frame {frame}" },
  fr: { nav_demo: "Démo", nav_download: "Télécharger", nav_releases: "Versions", hero_title: "Explorez le tracking avant l'installation.", hero_copy: "Une petite démo synthétique du flux. Vos vidéos, modèles et calibrations restent locaux dans l'application de bureau.", try_demo: "Essayer la démo", download_windows: "Télécharger l'installateur Windows", local_first: "Local-first par conception", no_upload: "Aucun envoi · aucun compte · aucune donnée privée", interactive_label: "APERÇU INTERACTIF", demo_title: "Réviser une image suivie", synthetic: "Données synthétiques", play: "Lire", frame: "Image", overlay: "Superposition", ready: "Prêt pour la révision", roi_none: "Aucune ROI", person: "Personne", visuals: "Couches visuelles", skeleton: "Squelette", boxes: "Boîte", zoom: "Zoom", roi: "ROI", clear: "Effacer", draw_roi: "Dessiner ROI", outside_mask: "Masque extérieur", analyze: "Analyser la personne", analysis_hint: "Choisissez une image et cliquez sur Analyser pour voir une métrique reproductible.", distribution: "DISTRIBUTION PUBLIQUE", download_title: "Installer le flux desktop complet", download_copy: "L'installateur web est un bootstrap léger. Il affiche le plan, reprend les téléchargements, vérifie SHA-256 et installe les composants TOTO atomiquement.", analyzed: "Métrique d'aperçu : {score}% de confiance · sujet Personne {person} · image {frame}" },
  de: { nav_demo: "Demo", nav_download: "Download", nav_releases: "Versionen", hero_title: "Tracking vor der Installation ausprobieren.", hero_copy: "Eine kleine synthetische Browser-Demo für den Ablauf. Videos, Modelle und Kalibrierungen bleiben in der Desktop-App lokal.", try_demo: "Demo testen", download_windows: "Windows-Installer laden", local_first: "Local-first entwickelt", no_upload: "Kein Upload · kein Konto · keine privaten Daten", interactive_label: "INTERAKTIVE VORSCHAU", demo_title: "Getracktes Bild prüfen", synthetic: "Synthetische Daten", play: "Abspielen", frame: "Frame", overlay: "Overlay", ready: "Bereit zur Prüfung", roi_none: "Keine ROI", person: "Person", visuals: "Sichtbare Ebenen", skeleton: "Skelett", boxes: "Box", zoom: "Zoom", roi: "ROI", clear: "Löschen", draw_roi: "ROI zeichnen", outside_mask: "Außenmaske", analyze: "Person analysieren", analysis_hint: "Frame wählen und Analysieren drücken, um eine reproduzierbare Vorschau-Metrik zu sehen.", distribution: "ÖFFENTLICHE VERTEILUNG", download_title: "Den vollständigen Desktop-Workflow installieren", download_copy: "Der Web-Installer ist ein kleiner Bootstrap. Er zeigt den echten Plan, setzt Downloads fort, prüft SHA-256 und installiert die TOTO-Komponenten atomar.", analyzed: "Vorschau-Metrik: {score}% Konfidenz · gerankte Person {person} · Frame {frame}" },
  ja: { nav_demo: "デモ", nav_download: "ダウンロード", nav_releases: "リリース", hero_title: "インストール前にトラッキングを体験。", hero_copy: "操作フローを試す小さな合成ブラウザデモです。動画、モデル、キャリブレーションはデスクトップアプリ内にローカル保存されます。", try_demo: "デモを試す", download_windows: "Windowsインストーラー", local_first: "ローカルファースト", no_upload: "アップロードなし · アカウント不要 · 個人データなし", interactive_label: "インタラクティブプレビュー", demo_title: "追跡フレームを確認", synthetic: "合成データ", play: "再生", frame: "フレーム", overlay: "オーバーレイ", ready: "確認の準備完了", roi_none: "ROIなし", person: "人物", visuals: "表示レイヤー", skeleton: "スケルトン", boxes: "バウンディングボックス", zoom: "ズーム", roi: "ROI", clear: "クリア", draw_roi: "ROIを描く", outside_mask: "外側マスク", analyze: "人物を解析", analysis_hint: "フレームを選び、解析を押すと再現可能なプレビュー指標を表示します。", distribution: "公開配布", download_title: "完全なデスクトップワークフローをインストール", download_copy: "ウェブインストーラーは小さなブートストラップです。実際のダウンロード計画を表示し、中断を再開し、SHA-256を検証してTOTOコンポーネントを原子的にインストールします。", analyzed: "プレビュー指標: 信頼度{score}% · ランク対象 人物{person} · フレーム{frame}" },
  zh: { nav_demo: "演示", nav_download: "下载", nav_releases: "版本", hero_title: "安装前先体验追踪。", hero_copy: "用于体验操作流程的小型合成浏览器演示。视频、模型和标定数据保留在桌面应用本地。", try_demo: "试用演示", download_windows: "下载 Windows 安装程序", local_first: "本地优先设计", no_upload: "不上传 · 无需账户 · 演示不含私有数据", interactive_label: "交互预览", demo_title: "查看追踪帧", synthetic: "合成数据", play: "播放", frame: "帧", overlay: "叠加层", ready: "准备查看", roi_none: "未选择 ROI", person: "人物", visuals: "可视图层", skeleton: "骨架", boxes: "边界框", zoom: "缩放", roi: "ROI", clear: "清除", draw_roi: "绘制 ROI", outside_mask: "外部遮罩", analyze: "分析人物", analysis_hint: "选择帧并点击分析，查看可复现的预览指标。", distribution: "公开分发", download_title: "安装完整桌面流程", download_copy: "网页安装程序是轻量引导程序。它显示实际下载计划、恢复中断下载、验证 SHA-256，并以原子方式安装固定版本的 TOTO 组件。", analyzed: "预览指标：置信度 {score}% · 排名人物 {person} · 帧 {frame}" },
  ru: { nav_demo: "Демо", nav_download: "Скачать", nav_releases: "Релизы", hero_title: "Попробуйте трекинг до установки.", hero_copy: "Небольшая синтетическая браузерная демонстрация рабочего процесса. Видео, модели и калибровки остаются локально в настольном приложении.", try_demo: "Открыть демо", download_windows: "Скачать установщик Windows", local_first: "Локальная обработка", no_upload: "Без загрузки · без аккаунта · без личных данных", interactive_label: "ИНТЕРАКТИВНЫЙ ПРОСМОТР", demo_title: "Проверка отслеживаемого кадра", synthetic: "Синтетические данные", play: "Воспроизвести", frame: "Кадр", overlay: "Наложение", ready: "Готово к проверке", roi_none: "ROI не выбрана", person: "Человек", visuals: "Визуальные слои", skeleton: "Скелет", boxes: "Рамка", zoom: "Масштаб", roi: "ROI", clear: "Очистить", draw_roi: "Нарисовать ROI", outside_mask: "Внешняя маска", analyze: "Анализировать человека", analysis_hint: "Выберите кадр и нажмите Анализ, чтобы увидеть воспроизводимую метрику.", distribution: "ПУБЛИЧНАЯ ДИСТРИБУЦИЯ", download_title: "Установите полный рабочий процесс", download_copy: "Веб-установщик — это небольшой загрузчик. Он показывает план, возобновляет прерванные загрузки, проверяет SHA-256 и атомарно устанавливает компоненты TOTO.", analyzed: "Метрика предпросмотра: доверие {score}% · ранжированный человек {person} · кадр {frame}" },
};

const $ = (id) => document.getElementById(id);
let locale = localStorage.getItem("toto-demo-language") || "en";
let playing = false;
let roi = null;
let roiMode = null;
let roiStart = null;

function t(key) { return (copy[locale] || copy.en)[key] || copy.en[key] || key; }
function translate() {
  document.querySelectorAll("[data-i18n]").forEach((node) => { node.textContent = t(node.dataset.i18n); });
  $("download-hero").href = RELEASE_INSTALLER;
  $("download-main").href = RELEASE_INSTALLER;
  document.documentElement.lang = locale;
  localStorage.setItem("toto-demo-language", locale);
}

function draw() {
  const canvas = $("viewer");
  const ctx = canvas.getContext("2d");
  const frame = Number($("frame").value);
  const zoom = Number($("zoom").value) / 100;
  const dark = document.body.classList.contains("dark");
  ctx.clearRect(0, 0, canvas.width, canvas.height);
  ctx.fillStyle = dark ? "#101c31" : "#e7eff8";
  ctx.fillRect(0, 0, canvas.width, canvas.height);
  ctx.save();
  ctx.translate(canvas.width / 2, canvas.height / 2);
  ctx.scale(zoom, zoom);
  ctx.translate(-canvas.width / 2, -canvas.height / 2);
  ctx.strokeStyle = dark ? "#29476b" : "#cbdced";
  ctx.lineWidth = 2;
  for (let x = 40; x < canvas.width; x += 80) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, canvas.height); ctx.stroke(); }
  for (let y = 40; y < canvas.height; y += 80) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(canvas.width, y); ctx.stroke(); }
  const sway = Math.sin(frame / 12) * 15;
  const personX = 480 + sway;
  const personY = 180 + Math.cos(frame / 18) * 9;
  if ($("boxes").checked) { ctx.strokeStyle = "#10bdc2"; ctx.lineWidth = 4; ctx.strokeRect(personX - 115, personY - 55, 230, 355); }
  if ($("overlay").checked && $("skeleton").checked) {
    const points = [[personX, personY], [personX - 34, personY + 45], [personX + 34, personY + 45], [personX, personY + 92], [personX - 57, personY + 145], [personX + 57, personY + 145], [personX - 78, personY + 225], [personX + 78, personY + 225], [personX - 40, personY + 298], [personX + 40, personY + 298]];
    const edges = [[0,1],[0,2],[0,3],[3,4],[3,5],[4,6],[5,7],[6,8],[7,9]];
    ctx.strokeStyle = "#0bbcc2"; ctx.fillStyle = "#ffffff"; ctx.lineWidth = 6; ctx.lineCap = "round";
    edges.forEach(([a,b]) => { ctx.beginPath(); ctx.moveTo(...points[a]); ctx.lineTo(...points[b]); ctx.stroke(); });
    points.forEach(([x,y]) => { ctx.beginPath(); ctx.arc(x, y, 7, 0, Math.PI * 2); ctx.fill(); ctx.stroke(); });
  }
  if (roi) { ctx.fillStyle = "rgba(16, 189, 194, .14)"; ctx.strokeStyle = "#f19a4a"; ctx.lineWidth = 3; ctx.fillRect(roi.x, roi.y, roi.w, roi.h); ctx.strokeRect(roi.x, roi.y, roi.w, roi.h); }
  ctx.restore();
  $("frame-value").textContent = `${frame} / 120`;
  $("zoom-value").textContent = `${Math.round(zoom * 100)}%`;
}

function canvasPoint(event) { const rect = $("viewer").getBoundingClientRect(); return { x: (event.clientX - rect.left) * 960 / rect.width, y: (event.clientY - rect.top) * 600 / rect.height }; }
$("language").value = locale;
$("language").addEventListener("change", (event) => { locale = event.target.value; translate(); draw(); });
$("theme").addEventListener("click", () => { document.body.classList.toggle("dark"); draw(); });
$("play").addEventListener("click", () => { playing = !playing; $("play").textContent = playing ? (locale === "es" ? "Pausa" : "Pause") : t("play"); });
$("frame").addEventListener("input", draw);
$("zoom").addEventListener("input", draw);
["overlay", "skeleton", "boxes"].forEach((id) => $(id).addEventListener("change", draw));
$("roi-draw").addEventListener("click", () => { roiMode = "draw"; $("viewer-message").textContent = locale === "es" ? "Arrastra en la vista para dibujar la ROI" : "Drag on the viewer to draw the ROI"; });
$("roi-mask").addEventListener("click", () => { roiMode = "mask"; $("viewer-message").textContent = locale === "es" ? "Arrastra en la vista para definir la máscara exterior" : "Drag on the viewer to define the outside mask"; });
$("clear-roi").addEventListener("click", () => { roi = null; roiMode = null; $("roi-status").textContent = t("roi_none"); draw(); });
$("viewer").addEventListener("pointerdown", (event) => { if (!roiMode) return; roiStart = canvasPoint(event); $("viewer").setPointerCapture(event.pointerId); });
$("viewer").addEventListener("pointermove", (event) => { if (!roiStart) return; const point = canvasPoint(event); roi = { x: Math.min(roiStart.x, point.x), y: Math.min(roiStart.y, point.y), w: Math.abs(point.x - roiStart.x), h: Math.abs(point.y - roiStart.y) }; draw(); });
$("viewer").addEventListener("pointerup", () => { if (!roiStart) return; roiStart = null; roiMode = null; $("roi-status").textContent = `${t("roi")}: ${Math.round(roi.w)} × ${Math.round(roi.h)} px`; $("viewer-message").textContent = t("ready"); });
$("analyze").addEventListener("click", () => { const frame = Number($("frame").value); const person = Number($("person").value) + 1; const score = 88 + (frame % 10); $("analysis").textContent = t("analyzed").replace("{score}", score).replace("{person}", person).replace("{frame}", frame); });
setInterval(() => { if (playing) { const slider = $("frame"); slider.value = Number(slider.value) >= 120 ? 1 : Number(slider.value) + 1; draw(); } }, 80);
translate();
draw();
